export const UPLOAD_MISC_DOC_REQUEST = "UPLOAD_MISC_DOC_REQUEST";
export const UPLOAD_MISC_DOC_SUCCESS = "UPLOAD_MISC_DOC_SUCCESS";
export const UPLOAD_MISC_DOC_FAIL = "UPLOAD_MISC_DOC_FAIL";

export const UPLOAD_ITR_DOC_REQUEST = "UPLOAD_ITR_DOC_REQUEST";
export const UPLOAD_ITR_DOC_SUCCESS = "UPLOAD_ITR_DOC_SUCCESS";
export const UPLOAD_ITR_DOC_FAIL = "UPLOAD_ITR_DOC_FAIL";

export const UPLOAD_GST_DOC_REQUEST = "UPLOAD_GST_DOC_REQUEST";
export const UPLOAD_GST_DOC_SUCCESS = "UPLOAD_GST_DOC_SUCCESS";
export const UPLOAD_GST_DOC_FAIL = "UPLOAD_GST_DOC_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"