export const ALL_TICEKTS_REQUEST = "ALL_TICEKTS_REQUEST"
export const ALL_TICEKTS_SUCCESS = "ALL_TICEKTS_SUCCESS"
export const ALL_TICEKTS_FAIL = "ALL_TICEKTS_FAIL"

export const TICKET_INFO_REQUEST = "TICKET_INFO_REQUEST"
export const TICKET_INFO_SUCCESS = "TICKET_INFO_SUCCESS"
export const TICKET_INFO_FAIL = "TICKET_INFO_FAIL"

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"